yaml
name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Connect to EC2 instance 
      env:  
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
        SSH_KEY:    ${{ secrets.SSH_KEY }}
      run:
        echo "$SSH_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -i deploy_key.pem ubuntu@$IP_ADDRESS
        echo "Connected to EC2 instance"
        source venv/bin/activate
        cd JaneBot
        nohup python3 main.py > bot.log 2>&1 &